import java.awt.Color;

public class Paints extends PixelTablet {
	
	public static void pixelPaint() {
		try {
			Thread.sleep(1000);
		} catch (InterruptedException e1) {
			// TODO Auto-generated catch block
			e1.printStackTrace();
		}
		cells[201].setBackground(Color.BLUE);
		cells[267].setBackground(Color.BLUE);
		cells[333].setBackground(Color.BLUE);
		cells[399].setBackground(Color.BLUE);
		cells[465].setBackground(Color.BLUE);
		cells[531].setBackground(Color.BLUE);
		cells[597].setBackground(Color.BLUE);
		cells[663].setBackground(Color.BLUE);
		cells[729].setBackground(Color.BLUE);
		cells[795].setBackground(Color.BLUE);
		cells[861].setBackground(Color.BLUE);
		cells[927].setBackground(Color.BLUE);
		cells[993].setBackground(Color.BLUE);
		cells[1059].setBackground(Color.BLUE);
		cells[202].setBackground(Color.BLUE);
		cells[203].setBackground(Color.BLUE);
		cells[204].setBackground(Color.BLUE);
		cells[205].setBackground(Color.BLUE);
		cells[206].setBackground(Color.BLUE);
		cells[272].setBackground(Color.BLUE);
		cells[338].setBackground(Color.BLUE);
		cells[404].setBackground(Color.BLUE);
		cells[470].setBackground(Color.BLUE);
		cells[536].setBackground(Color.BLUE);
		cells[535].setBackground(Color.BLUE);
		cells[534].setBackground(Color.BLUE);
		cells[533].setBackground(Color.BLUE);
		cells[532].setBackground(Color.BLUE);		
		cells[605].setBackground(Color.BLUE);
		cells[671].setBackground(Color.BLUE);
		cells[737].setBackground(Color.BLUE);
		cells[803].setBackground(Color.BLUE);
		cells[869].setBackground(Color.BLUE);
		cells[935].setBackground(Color.BLUE);
		cells[1001].setBackground(Color.BLUE);
		cells[1067].setBackground(Color.BLUE);
		cells[608].setBackground(Color.BLUE);
		cells[675].setBackground(Color.BLUE);
		cells[742].setBackground(Color.BLUE);
		cells[809].setBackground(Color.BLUE);
		cells[1070].setBackground(Color.BLUE);
		cells[1005].setBackground(Color.BLUE);
		cells[940].setBackground(Color.BLUE);
		cells[875].setBackground(Color.BLUE);
		cells[744].setBackground(Color.BLUE);
		cells[679].setBackground(Color.BLUE);
		cells[614].setBackground(Color.BLUE);
		cells[942].setBackground(Color.BLUE);
		cells[1009].setBackground(Color.BLUE);
		cells[1076].setBackground(Color.BLUE);
		cells[617].setBackground(Color.BLUE);
		cells[683].setBackground(Color.BLUE);
		cells[749].setBackground(Color.BLUE);
		cells[815].setBackground(Color.BLUE);
		cells[881].setBackground(Color.BLUE);
		cells[947].setBackground(Color.BLUE);
		cells[1013].setBackground(Color.BLUE);
		cells[1079].setBackground(Color.BLUE);
		cells[618].setBackground(Color.BLUE);
		cells[619].setBackground(Color.BLUE);
		cells[620].setBackground(Color.BLUE);
		cells[621].setBackground(Color.BLUE);
		cells[816].setBackground(Color.BLUE);
		cells[817].setBackground(Color.BLUE);
		cells[818].setBackground(Color.BLUE);
		cells[819].setBackground(Color.BLUE);
		cells[1080].setBackground(Color.BLUE);
		cells[1081].setBackground(Color.BLUE);
		cells[1082].setBackground(Color.BLUE);
		cells[1083].setBackground(Color.BLUE);
		cells[624].setBackground(Color.BLUE);
		cells[690].setBackground(Color.BLUE);
		cells[756].setBackground(Color.BLUE);
		cells[822].setBackground(Color.BLUE);
		cells[888].setBackground(Color.BLUE);
		cells[954].setBackground(Color.BLUE);
		cells[1020].setBackground(Color.BLUE);
		cells[1086].setBackground(Color.BLUE);
		cells[1087].setBackground(Color.BLUE);
		cells[1088].setBackground(Color.BLUE);
		cells[1089].setBackground(Color.BLUE);
		cells[1090].setBackground(Color.BLUE);
		try {
			Thread.sleep(1000);
		} catch (InterruptedException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		cells[1093].setBackground(Color.RED);
		cells[1027].setBackground(Color.RED);
		cells[961].setBackground(Color.RED);
		cells[895].setBackground(Color.RED);
		cells[829].setBackground(Color.RED);
		cells[763].setBackground(Color.RED);
		cells[697].setBackground(Color.RED);
		cells[631].setBackground(Color.RED);
		cells[565].setBackground(Color.RED);
		cells[499].setBackground(Color.RED);
		cells[433].setBackground(Color.RED);
		cells[367].setBackground(Color.RED);
		cells[301].setBackground(Color.RED);
		cells[235].setBackground(Color.RED);
		cells[236].setBackground(Color.RED);
		cells[237].setBackground(Color.RED);
		cells[238].setBackground(Color.RED);
		cells[239].setBackground(Color.RED);
		cells[240].setBackground(Color.RED);
		cells[306].setBackground(Color.RED);
		cells[372].setBackground(Color.RED);
		cells[438].setBackground(Color.RED);
		cells[504].setBackground(Color.RED);
		cells[570].setBackground(Color.RED);
		cells[569].setBackground(Color.RED);	
		cells[568].setBackground(Color.RED);
		cells[567].setBackground(Color.RED);
		cells[566].setBackground(Color.RED);
		cells[1101].setBackground(Color.RED);
		cells[1035].setBackground(Color.RED);
		cells[969].setBackground(Color.RED);
		cells[903].setBackground(Color.RED);
		cells[837].setBackground(Color.RED);
		cells[771].setBackground(Color.RED);
		cells[706].setBackground(Color.RED);
		cells[641].setBackground(Color.RED);
		cells[708].setBackground(Color.RED);
		cells[775].setBackground(Color.RED);
		cells[841].setBackground(Color.RED);
		cells[907].setBackground(Color.RED);
		cells[973].setBackground(Color.RED);
		cells[1039].setBackground(Color.RED);
		cells[1105].setBackground(Color.RED);
		cells[838].setBackground(Color.RED);
		cells[839].setBackground(Color.RED);
		cells[840].setBackground(Color.RED);
		cells[646].setBackground(Color.RED);
		cells[712].setBackground(Color.RED);
		cells[778].setBackground(Color.RED);
		cells[844].setBackground(Color.RED);
		cells[910].setBackground(Color.RED);
		cells[976].setBackground(Color.RED);
		cells[1042].setBackground(Color.RED);
		cells[1108].setBackground(Color.RED);
		cells[649].setBackground(Color.RED);
		cells[715].setBackground(Color.RED);
		cells[781].setBackground(Color.RED);
		cells[847].setBackground(Color.RED);
		cells[913].setBackground(Color.RED);
		cells[979].setBackground(Color.RED);
		cells[1045].setBackground(Color.RED);
		cells[1111].setBackground(Color.RED);
		cells[650].setBackground(Color.RED);
		cells[717].setBackground(Color.RED);
		cells[784].setBackground(Color.RED);
		cells[653].setBackground(Color.RED);
		cells[719].setBackground(Color.RED);
		cells[785].setBackground(Color.RED);
		cells[851].setBackground(Color.RED);
		cells[917].setBackground(Color.RED);
		cells[983].setBackground(Color.RED);
		cells[1049].setBackground(Color.RED);
		cells[1115].setBackground(Color.RED);
		cells[655].setBackground(Color.RED);
		cells[656].setBackground(Color.RED);
		cells[657].setBackground(Color.RED);
		cells[658].setBackground(Color.RED);
		cells[659].setBackground(Color.RED);
		cells[723].setBackground(Color.RED);
		cells[789].setBackground(Color.RED);
		cells[855].setBackground(Color.RED);
		cells[921].setBackground(Color.RED);
		cells[987].setBackground(Color.RED);
		cells[1053].setBackground(Color.RED);
		cells[1119].setBackground(Color.RED);
		
		for (int i=1188; i<cells.length; i++) {
			cells[i].setBackground(Color.DARK_GRAY);
		}
		
		for (int i=0; i<132; i++) {
			cells[i].setBackground(Color.DARK_GRAY);
		}
		
	}

}
